jenkinsJobs:
  - name: provision-ecs-cluster
    repo: git@github.com:aditya-mittal/bootcamp-infrastructure.git
    branch: master
    jenkinsFilePath: ecs-cluster/Jenkinsfile
    folder: environments
    runImmediately: false
  - name: build
    repo: git@github.com:aditya-mittal/fraud-checker-service.git
    branch: master
    jenkinsFilePath: Jenkinsfile
    folder: fraud-checker-service
    runImmediately: false