jenkinsJobs:
  - name: provision-ecs-cluster
    repo: git@github.com:aditya-mittal/bootcamp-infrastructure.git
    branch: master
    jenkinsFilePath: ecs-cluster/Jenkinsfile
    folder: environments
  - name: deploy-nginx
    repo: git@github.com:aditya-mittal/bootcamp-infrastructure.git
    branch: master
    jenkinsFilePath: ecs-service/Jenkinsfile
  - name: fraud-checker-service
    repo: git@github.com:aditya-mittal/fraud-checker-service.git
    branch: master
    jenkinsFilePath: Jenkinsfile
    githubHookTrigger: true